-- Migration: Create va_time_sessions table
-- Purpose: Track VA time sessions for time tracking and payroll
-- Date: 2025-04-02

-- Create va_time_sessions table
CREATE TABLE IF NOT EXISTS va_time_sessions (
  id SERIAL PRIMARY KEY,
  session_id TEXT UNIQUE NOT NULL,  -- UUID for each session
  va_name TEXT NOT NULL,
  date DATE NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  duration_minutes INTEGER,
  notes TEXT,
  is_active BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_va_sessions_va_name ON va_time_sessions(va_name);
CREATE INDEX IF NOT EXISTS idx_va_sessions_date ON va_time_sessions(date);
CREATE INDEX IF NOT EXISTS idx_va_sessions_is_active ON va_time_sessions(is_active);
CREATE INDEX IF NOT EXISTS idx_va_sessions_session_id ON va_time_sessions(session_id);

-- Enable RLS
ALTER TABLE va_time_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access" ON va_time_sessions FOR ALL USING (true) WITH CHECK (true);

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_va_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER va_sessions_updated_at_trigger
  BEFORE UPDATE ON va_time_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_va_sessions_updated_at();

-- Comments for documentation
COMMENT ON TABLE va_time_sessions IS 'Tracks VA work sessions for time tracking';
COMMENT ON COLUMN va_time_sessions.session_id IS 'UUID generated by frontend for each session';
COMMENT ON COLUMN va_time_sessions.va_name IS 'Name of the VA (e.g., Jaleel Sebastian)';
COMMENT ON COLUMN va_time_sessions.date IS 'Work date (YYYY-MM-DD)';
COMMENT ON COLUMN va_time_sessions.start_time IS 'Clock-in timestamp';
COMMENT ON COLUMN va_time_sessions.end_time IS 'Clock-out timestamp (null if active)';
COMMENT ON COLUMN va_time_sessions.duration_minutes IS 'Computed duration in minutes';
COMMENT ON COLUMN va_time_sessions.is_active IS 'True if session is currently active (clocked in)';
